# fly.toml app configuration file generated for transfer on 2023-09-13T10:43:12+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "transfer"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
